"""add_student_preferences

Revision ID: 139509aa8257
Revises: d4c00193daf3
Create Date: 2026-02-06 23:01:01.229505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139509aa8257'
down_revision: Union[str, Sequence[str], None] = 'd4c00193daf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('daily_target_minutes_weekday', sa.Integer(), nullable=True),
    sa.Column('daily_target_minutes_weekend', sa.Integer(), nullable=True),
    sa.Column('preferred_study_window_start', sa.Time(), nullable=True),
    sa.Column('preferred_study_window_end', sa.Time(), nullable=True),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', name='uq_student_preferences_student_id')
    )
    op.create_index(op.f('ix_student_preferences_id'), 'student_preferences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_preferences_id'), table_name='student_preferences')
    op.drop_table('student_preferences')
    # ### end Alembic commands ###
