"""add_plan_task_unique_constraint

Revision ID: 8e3d50a021f9
Revises: 3f9bf9c9bdd6
Create Date: 2026-02-05 14:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3d50a021f9'
down_revision: Union[str, Sequence[str], None] = '3f9bf9c9bdd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - add unique constraint to prevent duplicate tasks."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_plan_task',
        'plan_tasks',
        ['plan_id', 'date', 'topic_id', 'task_type']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - remove unique constraint."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_plan_task', 'plan_tasks', type_='unique')
    # ### end Alembic commands ###
