"""add_qbank_tables

Revision ID: 91830330e3d7
Revises: b4c5d6e7f8a9
Create Date: 2026-07-04 12:24:52.628769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91830330e3d7'
down_revision: Union[str, Sequence[str], None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('subtopic', sa.String(length=200), nullable=True),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_key', sa.String(length=1), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_citation', sa.String(length=500), nullable=True),
    sa.Column('predicted_diff', sa.Float(), nullable=True),
    sa.Column('empirical_diff', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_subject'), 'questions', ['subject'], unique=False)
    op.create_index(op.f('ix_questions_test'), 'questions', ['test'], unique=False)
    op.create_table('qbank_exam_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=20), nullable=False),
    sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('score_pct', sa.Float(), nullable=True),
    sa.Column('by_subject', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qbank_exam_sessions_id'), 'qbank_exam_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_qbank_exam_sessions_student_id'), 'qbank_exam_sessions', ['student_id'], unique=False)
    op.create_table('question_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_attempts_answered_at'), 'question_attempts', ['answered_at'], unique=False)
    op.create_index(op.f('ix_question_attempts_id'), 'question_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_question_attempts_question_id'), 'question_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_attempts_student_id'), 'question_attempts', ['student_id'], unique=False)
    op.create_table('srs_state',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('next_review', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'question_id')
    )
    op.create_index(op.f('ix_srs_state_next_review'), 'srs_state', ['next_review'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_srs_state_next_review'), table_name='srs_state')
    op.drop_table('srs_state')
    op.drop_index(op.f('ix_question_attempts_student_id'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_question_id'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_id'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_answered_at'), table_name='question_attempts')
    op.drop_table('question_attempts')
    op.drop_index(op.f('ix_qbank_exam_sessions_student_id'), table_name='qbank_exam_sessions')
    op.drop_index(op.f('ix_qbank_exam_sessions_id'), table_name='qbank_exam_sessions')
    op.drop_table('qbank_exam_sessions')
    op.drop_index(op.f('ix_questions_test'), table_name='questions')
    op.drop_index(op.f('ix_questions_subject'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
