"""add_processed_at_to_event_logs

Revision ID: 9f2a6b3c7d8e
Revises: 8e3d50a021f9
Create Date: 2026-02-05 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2a6b3c7d8e'
down_revision: Union[str, Sequence[str], None] = '8e3d50a021f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - add processed_at column to event_logs."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_logs', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_event_logs_processed_at'), 'event_logs', ['processed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - remove processed_at column."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_logs_processed_at'), table_name='event_logs')
    op.drop_column('event_logs', 'processed_at')
    # ### end Alembic commands ###
