"""add_notification_quiet_hours_columns

Revision ID: a102ae79a7f0
Revises: 139509aa8257
Create Date: 2026-02-06 23:12:09.198508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a102ae79a7f0'
down_revision: Union[str, Sequence[str], None] = '139509aa8257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_notifications_next_attempt_at'), 'notifications', ['next_attempt_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_next_attempt_at'), table_name='notifications')
    op.drop_column('notifications', 'attempts')
    op.drop_column('notifications', 'next_attempt_at')
    # ### end Alembic commands ###
