"""update_coach_messages

Revision ID: d4c00193daf3
Revises: d39024110fec
Create Date: 2026-02-06 19:05:41.985992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4c00193daf3'
down_revision: Union[str, Sequence[str], None] = 'd39024110fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_messages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('coach_messages', sa.Column('workflow_run_id', sa.Integer(), nullable=True))
    op.add_column('coach_messages', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('coach_messages', 'tone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coach_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_coach_messages_created_at'), 'coach_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_coach_messages_read_at'), 'coach_messages', ['read_at'], unique=False)
    op.create_index(op.f('ix_coach_messages_student_id'), 'coach_messages', ['student_id'], unique=False)
    op.create_index(op.f('ix_coach_messages_user_id'), 'coach_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_coach_messages_workflow_run_id'), 'coach_messages', ['workflow_run_id'], unique=False)
    op.create_unique_constraint('uq_user_workflow_run', 'coach_messages', ['user_id', 'workflow_run_id'])
    op.drop_constraint(op.f('coach_messages_run_id_fkey'), 'coach_messages', type_='foreignkey')
    op.drop_constraint(op.f('coach_messages_student_id_fkey'), 'coach_messages', type_='foreignkey')
    op.create_foreign_key(None, 'coach_messages', 'student_profiles', ['student_id'], ['id'])
    op.create_foreign_key(None, 'coach_messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'coach_messages', 'workflow_runs', ['workflow_run_id'], ['id'])
    op.drop_column('coach_messages', 'is_read')
    op.drop_column('coach_messages', 'run_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_messages', sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('coach_messages', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'coach_messages', type_='foreignkey')
    op.drop_constraint(None, 'coach_messages', type_='foreignkey')
    op.drop_constraint(None, 'coach_messages', type_='foreignkey')
    op.create_foreign_key(op.f('coach_messages_student_id_fkey'), 'coach_messages', 'users', ['student_id'], ['id'])
    op.create_foreign_key(op.f('coach_messages_run_id_fkey'), 'coach_messages', 'workflow_runs', ['run_id'], ['id'])
    op.drop_constraint('uq_user_workflow_run', 'coach_messages', type_='unique')
    op.drop_index(op.f('ix_coach_messages_workflow_run_id'), table_name='coach_messages')
    op.drop_index(op.f('ix_coach_messages_user_id'), table_name='coach_messages')
    op.drop_index(op.f('ix_coach_messages_student_id'), table_name='coach_messages')
    op.drop_index(op.f('ix_coach_messages_read_at'), table_name='coach_messages')
    op.drop_index(op.f('ix_coach_messages_created_at'), table_name='coach_messages')
    op.alter_column('coach_messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('coach_messages', 'tone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('coach_messages', 'read_at')
    op.drop_column('coach_messages', 'workflow_run_id')
    op.drop_column('coach_messages', 'user_id')
    # ### end Alembic commands ###
